{% set name = "kedro-datasets" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro-datasets-{{ version }}.tar.gz
#  sha256: 7b8b376d8616b6ae6e1a6bd8ba01d32a0c4f385d4fab884d3e3ee536a9b1d49b
#  git_url: https://github.com/kedro-org/kedro-plugins.git
#  git_tag: main
#  git_depth: 1
  path: ../

build:
  skip: true  # [py>=38 or py2k or py<37]
  skip: true  # [win or osx]
#  script: mkdir -p $PREFIX/jars && cp -R jars/*.jar $PREFIX/jars
  script: {{ PYTHON }} -m pip install . -vv
  number: 6

requirements:
  host:
    - pip
    - python >=3.7,<3.8
    - setuptools >=38.0,<60
  run:
    - kedro >=0.18.4,<0.19.0
    - kedro-mlflow >=0.11.4
    - kedro-airflow >=0.5.1
#    - kedro-viz >=5.1.1

    - python >=3.7,<3.8
    - adlfs >=2021.7.1 #<=2022.2
    - bandit >=1.6.2 #<2.0,
    - biopython >=1.73 #,<2
    - dask-core >=2021.10 #,<2022
    - dill >=0.3.1 #,<0.4
    - filelock >=3.4.0 #<4.0,
    - gcsfs >=2021.4 #<=2022.1,
    - geopandas >=0.6.0 #<1.0,
    - python-hdfs >=2.5.8 #<3.0,
    - holoviews >=1.13.0
    - ipython >=7.31.1 #<8.0,
    - jinja2 >=3.0.0 #, <3.1.0
    - joblib >=0.14
    - jupyterlab >=3.0 #,<4
    - jupyter >=1.0 #,<2
    - lxml >=4.6 #,<5
    - memory_profiler >=0.50.0 #<1.0,
    - networkx >=2.4 #,<3
    - openpyxl >=3.0.3 #<4.0,
    - pandas-gbq >=0.12.0 #<1.0,
    - pandas >=1.3 #,<2
    - pillow >=9.0 #,<10
    - plotly >=4.8.0 #<6.0,
    - psutil >=5.8.0 #,<6.0.0
    - pyarrow >=1.0 #<11.0,
    - pylint >=2.5.2 # <3.0,
    - pyproj >=3.0 #,<4
    - pyspark <4.0,>=2.2  # [not win]
    - redis-py >=4.1 #,<5
    - requests >=2.20 #,<3
    - s3fs >=0.3.0 #,<0.5
    - sqlalchemy >=1.2 #,<2
    - tensorflow >=2.0,<3  # [not win]
    - xlsxwriter >=1.0 #,<2
    - pytables >=3.6,<4  # [not win]
    - matplotlib-base <3.6,>=3.0.3  # [py<39]

# Test Build Only by Adding Airflow & MLFlow
    - airflow >=2.4.2
    - mlflow >=1.0.0,<2.0.0
    - great-expectations >=0.15.20
    - pydeequ >=1.0.1

test:
  imports:
    - kedro_datasets

about:
  home: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets
  summary: Kedro-Datasets is where you can find all of Kedro's data connectors.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706


##
## mamba create -n kedro-datasets  "python==3.7.12" "pip" "setuptools >=38.0,<60" "pyspark==2.3.2" "nodejs>=18.0,<19.0" "kedro >=0.18.4,<0.19.0" "kedro-mlflow >=0.11.4" "kedro-airflow >=0.5.1" "kedro-viz >=5.1.1" "python >=3.7,<3.8" "adlfs >=2021.7.1" "bandit >=1.6.2" "biopython >=1.73" "dask-core >=2021.10" "dill >=0.3.1" "filelock >=3.4.0" "gcsfs >=2021.4" "geopandas >=0.6.0" "python-hdfs >=2.5.8" "holoviews >=1.13.0" "ipython >=7.31.1" "jinja2 >=3.0.0" "joblib >=0.14" "jupyterlab >=3.0" "jupyter >=1.0" "lxml >=4.6" "memory_profiler >=0.50.0" "networkx >=2.4" "openpyxl >=3.0.3" "pandas-gbq >=0.12.0" "pandas >=1.3 " "pillow >=9.0" "plotly >=4.8.0" "psutil >=5.8.0" "pyarrow >=1.0" "pylint >=2.5.2" "pyproj >=3.0" "pyspark <4.0,>=2.2" "redis-py >=4.1" "requests >=2.20 " "s3fs >=0.3.0" "sqlalchemy >=1.2" "tensorflow >=2.0" "xlsxwriter >=1.0" "pytables >=3.6,<4" "matplotlib-base <3.6,>=3.0.3" "airflow >=2.4.2" "mlflow >=1.0.0,<2.0.0" "great-expectations >=0.15.20" "pydeequ >=1.0.1"
##
